FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@9 --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma/

RUN pnpm install
RUN npx prisma generate

EXPOSE 3001

CMD ["pnpm", "start:dev"]
