version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: damp-local-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: damp_db
    ports:
      - "5435:5432"
    volumes:
      - damp_local_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d damp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  damp_local_db_data:
